name: Tests

on:
  workflow_dispatch:
    inputs:
      tests_mark:
        description: API or/and UI
        required: true
        type: choice
        default: all
        options:
          - all
          - API
          - UI
  push:
    branches:
      - main    # Запускать workflow при пуше в main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Copy source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate Allure results
        run: pytest -v